service:
  name: serverlesschallenge

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  region: us-east-1

functions:
  createUser:
    handler: src/functions/createUser.handle
    events:
      - http:
          path: /todos/{userid}
          method: POST
          cors: true
  showUser:
    handler: src/functions/showUser.handle
    events:
      - http:
          path: /todos/{userid}
          method: GET
          cors: true

resources:
  Resources:
    dbUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
